//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRANCH()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.FINANCIAL_RECORD = new HashSet<FINANCIAL_RECORD>();
            this.MEMBERSHIPs = new HashSet<MEMBERSHIP>();
            this.BRANCH_PERFORMANCE = new HashSet<BRANCH_PERFORMANCE>();
        }
    
        public int ID { get; set; }
        public string branch_name { get; set; }
        public string branch_city { get; set; }
        public string branch_address { get; set; }
        public string branch_district { get; set; }
        public string branch_contact_number { get; set; }
        public Nullable<int> branch_capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCIAL_RECORD> FINANCIAL_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERSHIP> MEMBERSHIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRANCH_PERFORMANCE> BRANCH_PERFORMANCE { get; set; }
    }
}
