//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH_PERFORMANCE
    {
        public int ID { get; set; }
        public int BRANCHID { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public decimal revenue { get; set; }
        public decimal expenses { get; set; }
        public Nullable<decimal> net_profit { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
    }
}
