//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ENROLLMENT
    {
        public int ID { get; set; }
        public int MEMBERID { get; set; }
        public int COURSE_CATEGORYID { get; set; }
        public System.DateTime enrollment_date { get; set; }
    
        public virtual COURSE_CATEGORY COURSE_CATEGORY { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
