//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int employee_id { get; set; }
        public string employee_first_name { get; set; }
        public string employee_last_name { get; set; }
        public string position { get; set; }
        public System.DateTime hire_date { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> branch_id { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
    }
}
