//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCIAL_RECORD
    {
        public int ID { get; set; }
        public int BRANCHID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_method { get; set; }
        public string transaction_type { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
