//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.COURSE_ENROLLMENT = new HashSet<COURSE_ENROLLMENT>();
            this.FINANCIAL_RECORD = new HashSet<FINANCIAL_RECORD>();
            this.MEMBERSHIPs = new HashSet<MEMBERSHIP>();
        }
    
        public int member_id { get; set; }
        public string member_first_name { get; set; }
        public string member_last_name { get; set; }
        public string member_email { get; set; }
        public string member_phone_number { get; set; }
        public string member_address { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string member_gender { get; set; }
        public System.DateTime member_join_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_ENROLLMENT> COURSE_ENROLLMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCIAL_RECORD> FINANCIAL_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERSHIP> MEMBERSHIPs { get; set; }
    }
}
