//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP
    {
        public int ID { get; set; }
        public int MEMBERID { get; set; }
        public int BRANCHID { get; set; }
        public string membership_type { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public decimal fee_amount { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
