//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMPE232Entities : DbContext
    {
        public CMPE232Entities()
            : base("name=CMPE232Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<BRANCH_PERFORMANCE> BRANCH_PERFORMANCE { get; set; }
        public virtual DbSet<COURSE_CATEGORY> COURSE_CATEGORY { get; set; }
        public virtual DbSet<COURSE_ENROLLMENT> COURSE_ENROLLMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<FINANCIAL_RECORD> FINANCIAL_RECORD { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MEMBERSHIP> MEMBERSHIPs { get; set; }
    }
}
